ApiRootUrl: "http://10.0.4.2:5000/api"
ClientUpdates:
  CycleSleep: 30000
  IsEnabled: true
ClientResults:
  IsEnabled: false
  CycleSleep: 30000
Id:
  IsEnabled: true
  Format: "id"
  FormatValue: "MACHINE-UUID-HERE"
EncodeHeaders: false
